# Лабораторная работа №9 по курсу "Методы и средства передачи информации"

_Выполнил студент группы А-07-18 Востриков Роман_

## Задание 1

Построить таблицу синдромов для кода Хэмминга (7, 4).

### Решение

Код Хэмминг(7,4) имеет следующие порождающую и проверочную матрицу:
$$
G=
\begin{pmatrix}
1 & 0 & 0 & 0 & 1 & 0 & 1 \\
0 & 1 & 0 & 0 & 1 & 1 & 1 \\ 
0 & 0 & 1 & 0 & 1 & 1 & 0 \\ 
0 & 0 & 0 & 1 & 0 & 1 & 1 \\ 
\end{pmatrix}, \;
H =
\begin{pmatrix}
1 & 1 & 1 & 0 & 1 & 0 & 0 \\
0 & 1 & 1 & 1 & 0 & 1 & 0 \\ 
1 & 1 & 0 & 1 & 0 & 0 & 1 \\
\end{pmatrix}
$$

Получим таблицу кодовых слов $T = A\times G$, где $A$ - матрица из всех сообщений длины 4, записанных по строкам.

In [1]:
import numpy as np

In [2]:
G = np.array([[1, 0, 0, 0, 1, 0, 1],
              [0, 1, 0, 0, 1, 1, 1],
              [0, 0, 1, 0, 1, 1, 0],
              [0, 0, 0, 1, 0, 1, 1]])

H = np.array([[1, 1, 1, 0, 1, 0, 0],
              [0, 1, 1, 1, 0, 1, 0],
              [1, 1, 0, 1, 0, 0, 1]])

A = np.array([[0, 0, 0, 0],
              [0, 0, 0, 1],
              [0, 0, 1, 0],
              [0, 0, 1, 1],
              [0, 1, 0, 0],
              [0, 1, 0, 1],
              [0, 1, 1, 0],
              [0, 1, 1, 1],
              [1, 0, 0, 0],
              [1, 0, 0, 1],
              [1, 0, 1, 0],
              [1, 0, 1, 1],
              [1, 1, 0, 0],
              [1, 1, 0, 1],
              [1, 1, 1, 0],
              [1, 1, 1, 1]])

np.mod(A @ G, 2)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 1],
       [0, 0, 1, 0, 1, 1, 0],
       [0, 0, 1, 1, 1, 0, 1],
       [0, 1, 0, 0, 1, 1, 1],
       [0, 1, 0, 1, 1, 0, 0],
       [0, 1, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 1],
       [1, 0, 0, 1, 1, 1, 0],
       [1, 0, 1, 0, 0, 1, 1],
       [1, 0, 1, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0],
       [1, 1, 0, 1, 0, 0, 1],
       [1, 1, 1, 0, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1]])

$$
C = T^T=
\begin{pmatrix}
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 \\
0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 \\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 \\
0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 \\
0 & 1 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 0 & 1 \\
0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 \\
\end{pmatrix}
$$

Возьмем вектор $w_1$, которого нет в $C$, и с помощью него получим $C_1$, из которого найдем лидер $L_1$:
$$
w_1 = 
\begin{pmatrix}
1 \\
0 \\
0 \\
0 \\
0 \\
0 \\
0 \\
\end{pmatrix};
C_1 =
\begin{pmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 \\
0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 \\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 \\
0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 \\
0 & 1 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 0 & 1 \\
0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 \\
\end{pmatrix};
L_1 = 
\begin{pmatrix}
1 \\
0 \\
0 \\
0 \\
0 \\
0 \\
0 \\
\end{pmatrix};
$$

Теперь найдем синдром $S_1=L_1^T\times H^T = \begin{pmatrix} 1 & 0 &1\end{pmatrix}$

In [3]:
L1T = np.array([1, 0, 0, 0, 0, 0, 0])
np.mod(L1T @ H.T, 2)

array([1, 0, 1])

Возьмем вектор $w_2$, которого нет в $C$, и с помощью него получим $C_2$, из которого найдем лидер $L_2$:
$$
w_2 = 
\begin{pmatrix}
1 \\
1 \\
0 \\
0 \\
0 \\
0 \\
0 \\
\end{pmatrix};
C_2 =
\begin{pmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 \\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 \\
0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 \\
0 & 1 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 0 & 1 \\
0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 \\
\end{pmatrix};
L_2 = 
\begin{pmatrix}
0 \\
0 \\
0 \\
0 \\
0 \\
1 \\
0 \\
\end{pmatrix};
$$

Теперь найдем синдром $S_2=L_2^T\times H^T = \begin{pmatrix} 0 & 1 & 0\end{pmatrix}$

In [4]:
L2T = np.array([0, 0, 0, 0, 0, 1, 0])
np.mod(L2T @ H.T, 2)

array([0, 1, 0])

Возьмем вектор $w_3$, которого нет в $C$, и с помощью него получим $C_3$, из которого найдем лидер $L_3$:
$$
w_3 = 
\begin{pmatrix}
1 \\
1 \\
1 \\
0 \\
0 \\
0 \\
0 \\
\end{pmatrix};
C_3 =
\begin{pmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 \\
1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 \\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 \\
0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 \\
0 & 1 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 0 & 1 \\
0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 \\
\end{pmatrix};
L_3 = 
\begin{pmatrix}
0 \\
0 \\
0 \\
0 \\
1 \\
0 \\
0 \\
\end{pmatrix};
$$

Теперь найдем синдром $S_3=L_3^T\times H^T = \begin{pmatrix} 1 & 0 & 0\end{pmatrix}$

In [5]:
L3T = np.array([0, 0, 0, 0, 1, 0, 0])
np.mod(L3T @ H.T, 2)

array([1, 0, 0])

Возьмем вектор $w_4$, которого нет в $C$, и с помощью него получим $C_4$, из которого найдем лидер $L_4$:
$$
w_4 = 
\begin{pmatrix}
1 \\
1 \\
1 \\
1 \\
0 \\
0 \\
0 \\
\end{pmatrix};
C_4 =
\begin{pmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 \\
1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 \\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 \\
0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 \\
0 & 1 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 0 & 1 \\
0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 \\
\end{pmatrix};
L_4 = 
\begin{pmatrix}
0 \\
1 \\
0 \\
0 \\
0 \\
0 \\
0 \\
\end{pmatrix};
$$

Теперь найдем синдром $S_4=L_4^T\times H^T = \begin{pmatrix} 1 & 1 & 1\end{pmatrix}$

In [6]:
L4T = np.array([0, 1, 0, 0, 0, 0, 0])
np.mod(L4T @ H.T, 2)

array([1, 1, 1])

Возьмем вектор $w_5$, которого нет в $C$, и с помощью него получим $C_5$, из которого найдем лидер $L_5$:
$$
w_5 = 
\begin{pmatrix}
1 \\
1 \\
1 \\
1 \\
1 \\
0 \\
0 \\
\end{pmatrix};
C_5 =
\begin{pmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 \\
1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 \\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 \\
1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 \\
0 & 1 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 0 & 1 \\
0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 \\
\end{pmatrix};
L_5 = 
\begin{pmatrix}
0 \\
0 \\
0 \\
1 \\
0 \\
0 \\
0 \\
\end{pmatrix};
$$

Теперь найдем синдром $S_5=L_5^T\times H^T = \begin{pmatrix} 0 & 1 & 1\end{pmatrix}$

In [7]:
L5T = np.array([0, 0, 0, 1, 0, 0, 0])
np.mod(L5T @ H.T, 2)

array([0, 1, 1])

Возьмем вектор $w_6$, которого нет в $C$, и с помощью него получим $C_6$, из которого найдем лидер $L_6$:
$$
w_6 = 
\begin{pmatrix}
1 \\
1 \\
1 \\
1 \\
1 \\
1 \\
0 \\
\end{pmatrix};
C_6 =
\begin{pmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 \\
1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 \\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 \\
1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 \\
1 & 0 & 0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 & 1 & 0 \\
0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 \\
\end{pmatrix};
L_6 = 
\begin{pmatrix}
0 \\
0 \\
0 \\
0 \\
0 \\
0 \\
1 \\
\end{pmatrix};
$$

Теперь найдем синдром $S_6=L_6^T\times H^T = \begin{pmatrix} 0 & 0 & 1\end{pmatrix}$

In [8]:
L6T = np.array([0, 0, 0, 0, 0, 0, 1])
np.mod(L6T @ H.T, 2)

array([0, 0, 1])

Возьмем вектор $w_7$, которого нет в $C$, и с помощью него получим $C_7$, из которого найдем лидер $L_7$:
$$
w_7 = 
\begin{pmatrix}
0 \\
0 \\
1 \\
0 \\
0 \\
0 \\
0 \\
\end{pmatrix};
C_7 =
\begin{pmatrix}
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 \\
1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 \\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 \\
0 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & 1 & 1 \\
0 & 1 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 0 & 1 \\
0 & 1 & 0 & 1 & 1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 0 & 1 & 0 & 1 \\
\end{pmatrix};
L_7 = 
\begin{pmatrix}
0 \\
0 \\
1 \\
0 \\
0 \\
0 \\
0 \\
\end{pmatrix};
$$

Теперь найдем синдром $S_7=L_7^T\times H^T = \begin{pmatrix} 1 & 1 & 0\end{pmatrix}$

In [9]:
L7T = np.array([0, 0, 1, 0, 0, 0, 0])
np.mod(L7T @ H.T, 2)

array([1, 1, 0])

#### Таблица синдромов
|Синдром|$(1\:0\:1)$|$(1\:1\:1)$|$(1\:1\:0)$|$(0\:1\:1)$|$(1\:0\:0)$|$(0\:1\:0)$|$(0\:0\:1)$|
|:-----:|:---------:|:---------:|:---------:|:---------:|:---------:|:---------:|:---------:|
|Лидер соотв. смежного класса|1000000|0100000|0010000|0001000|0000100|0000010|0000001|
|Номер позиции с ошибкой| 1|2|3|4|5|6|7|

## Задание 2

Составить программу, которая выводит смежный класс и лидеров смежного класса. Таблица кодовых слов и некодовое слово вводится в программу.

### Решение

Для решениея задачи реализуем следующие функции (w представлен вектором-строкой для удобства ввода):

In [10]:
# проверка, является ли вектор w (строка) кодовым словом таблицы С
def is_codeword(w, C):
    return w.tolist() in C.T.tolist()

In [11]:
# нахождение смежного класса для некодового слова w (представленного вектором-строкой) по таблице кодовых слов C
def get_adjoining_class(w, C):
    if not is_codeword(w, C):
        return np.mod((C.T + w).T, 2)
    else: 
        raise Exception("w является кодовым словом")

In [12]:
# определение веса как количества единиц в кодовом слове
def code_weight(word):
    return np.count_nonzero(word)

In [13]:
def get_leaders(C):
    weights = np.apply_along_axis(code_weight, 0, C)
    l_weight = weights.min()
    return C.T[np.where(weights == l_weight)]

Для создания интерфейса нам понадобятся вспомогательные функции:

In [14]:
# преобразование строки в вектор 
def to_vector(s):
    res = map(int, filter(None, s.split(' ')))
    return np.array(list(res), dtype='i8')

In [21]:
# преобразование текста в матрицу
def to_matrix(t):
    rows = filter(None, t.split('\n'))
    m = [to_vector(r) for r in rows]
    return np.array(m)

In [38]:
# преобразование матрицы в код LaTeX для форматированного вывода
def latex_mat(m):
    l = m.tolist()
    rows = [r"&".join(str(i) for i in row) for row in l]
    inner = r"\\".join(rows)
    return r"\begin{pmatrix}"+inner+r"\end{pmatrix}"

In [31]:
# преобразование массива в код LaTeX вектора-столбца
def latex_cvector(v):
    l = v.tolist()
    inner = r"\\".join([str(i) for i in l])
    return r"\begin{pmatrix}"+inner+r"\end{pmatrix}"

Теперь можно объединить реализованные функции в программу с интерактивным интерфейсом:

In [50]:
import ipywidgets as widgets
from IPython.display import Latex

In [52]:
c = widgets.Textarea(
    value='',
    placeholder='Введите матрицу кодовой таблицы, разделяя числа пробелами',
    description='C:',
)
w = widgets.Text(
    value='',
    placeholder='Введите некодовое слово, разделяя числа пробелами',
    description='w:',
)

In [71]:
def adj_class_leaders(w, C):
    # переходим от строкового представления к массивам
    w = to_vector(w)
    C = to_matrix(C)
    
    adj_C = get_adjoining_class(w, C)
    leaders = get_leaders(adj_C)
    
    part_1 = fr"Смежный класс:$$C_w={latex_mat(adj_C)}$$"
    
    part_2 = "Лидер(ы):$${}$$".format(r',\:'.join(f'L_{i}={latex_cvector(l)}' for i, l in enumerate(leaders)))
    display(Latex(part_1+part_2)) 

In [74]:
ui = widgets.HBox([c, w])
out = widgets.interactive(adj_class_leaders, {'manual': True}, w=w, C=c)

display(out)

interactive(children=(Text(value='1 1 1 1 1 1 0', description='w:', placeholder='Введите некодовое слово, разд…

## Вывод

В ходе данной лабораторной работы было изучено декодирование по синдрому, составление таблицы синдромов с помощью смежных классов и их лидеро, позволяющая определить место ошибки в закодированном слове. Была написана программа для нахождения смежного класса и его лидера при известной таблице кодовых слов и поступающем на вход некодовом слове. 